name: "Release APK"

env:
  main_project_module: app

on:
  # Allows to run this workflow automatically when a tag is pushed
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code at the latest commit in branch
        id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Setup and validate gradle wrapper # Will automatically perform wrapper validation on each execution.
        uses: gradle/actions/setup-gradle@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/jars-3
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create Github Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          tag: ${{ github.ref_name }}
        run: |
          gh auth login --with-token <<< "$GH_PAT"
          gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="$tag" \
          --generate-notes

      - name: Upload Debug APK to Github Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          tag: ${{ github.ref_name }}
        run: |
          gh auth login --with-token <<< "$GH_PAT"
          gh release upload "$tag" ./app/build/outputs/apk/debug/app-debug.apk --clobber
