name: Build PR APK

env:
  MAIN_PROJECT_MODULE: "app"
  JAVA_VERSION: "17"

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main

jobs:
  build-and-upload-apk:
    runs-on: ubuntu-latest
    outputs:
      apkUrl: ${{ steps.upload-artifacts.outputs.artifact-url }}
    steps:
      - name: Checkout code at the latest commit in branch
        id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

  comment:
      needs: build-and-upload-apk
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - name: Update Comment
          env:
            PR_NUMBER: ${{ github.event.number }}
            APK_URL: "${{ needs.build-and-upload-apk.outputs.apkUrl }}"
          uses: peter-evans/create-or-update-comment@v4
          with:
            issue-number: ${{ env.PR_NUMBER }}
            edit-mode: replace
            body: |
              ✅ Build Successful! You can find a link to the downloadable APK below:
              
              | Name     | Link                    |
              | -------- | ----------------------- |
              | Download | ${{ env.APK_URL }} |
