name: Test Label Event

on:
  pull_request:
    types: [labeled]

jobs:
  test-label-event:
    runs-on: ubuntu-latest
    steps:
      - name: Set Label Name
        run: echo "LABEL_NAME=${{ github.event.label.name }}" >> $GITHUB_ENV
        
      - name: Check Label Event
        run: |
          echo 'Label event triggered: '${{ LABEL_NAME }}