name: PR labeled builds

env:
  main_project_module: app

on:
  pull_request:
    branches: ['main']
    types: [labeled]

jobs:
  build-and-comment:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Build APK') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Your APK building commands here...
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 7  # Retain the artifact for 7 days

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: app-release.apk