name: "Unit tests"

on:
  # Allows to run this workflow when a commit it pushed to the branch
  push:
    branches:
      - main
  # Allows to run this workflow when a Pull Request is made with the set target branch
  pull_request:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest
