name: "Validate Gradle Wrapper"
on:
  # Allows to run this workflow when a commit it pushed to the specified branches
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  # Allows to run this workflow when a Pull Request is made with the set target branches
  pull_request:
    #
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at the latest commit in branch
        id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup and validate gradle wrapper # Will automatically perform wrapper validation on each execution.
        uses: gradle/actions/setup-gradle@v4
