name: "Validate Gradle Wrapper"

on:
  # Allows to run this workflow when a commit it pushed to the branch
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  # Allows to run this workflow when a Pull Request is made with the set target branch
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - uses: gradle/actions/wrapper-validation@v3
